---
services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    # cap_add:
    #   - NET_ADMIN
    volumes:
      - ./logs/fromnet:/tmp/fromnet
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      # - /path/to/syslog-ng/config:/config
      # - /path/to/log:/var/log #optional

    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped
